### PR TITLE
Reuse existing tokio runtime if one exists

### LINKED ISSUE #29: Only create/enter new runtime if one does not already exist?
From my reading of the code, `Compat` futures will unconditionally create and enter a new single-threaded tokio runtime. This seems potentially inefficient if a tokio runtime (maybe a multi-threaded one) already exists.

Would it be possible to check if a runtime already exists before entering a new one?

### PR DESCRIPTION
**Pull request by bonsairobo**
Fixes #29

### CODE REVIEW

**Review by notgull — CHANGES_REQUESTED** [review]
Can you add a test for the case where the handle is polled after the original runtime has exited?

**Comment by bonsairobo** [comment]
@notgull I also tried adding this test:

```rust
    #[test]
    fn fallback_runtime_is_created_if_none_exists() {
        futures::executor::block_on(async { println!("foo") }.compat());

        assert!(TOKIO1.fallback_rt.is_some());
    }
```

But I realized unit testing this is kind of challenging since all tests are running in parallel, and creating a runtime in one test might affect the outcome of a different test.

I could make them integration tests to run them in separate processes, although I would need some public API to inspect whether the fallback runtime was created.

**Comment by flisky** [comment]
Anything I can help to push this forward? I have a perfect user case when using both [uniffi](https://github.com/mozilla/uniffi-rs/blob/main/docs/manual/src/kotlin/gradle.md#advise-on-rust-java-interop) and [rustls-platform-verifier](https://github.com/rustls/rustls-platform-verifier/pull/63#issuecomment-2125127857).

**Comment by notgull** [comment]
Sorry, this one fell through the cracks. I'll review it once I have time.

**Review by notgull — APPROVED** [review]

**Pull request merged**
